source 'https://github.com/CocoaPods/Specs.git'

target 'MMTestServerPlugin', :exclusive => false do
end

target 'Test Target', :exclusive => true do
  pod "MMTestServerPlugin", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "MMTestServerPlugin", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
